[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget unzip python3 python3-pip",
    "wget https://github.com/XTLS/Xray-core/releases/download/v1.8.4/Xray-linux-64.zip -O /tmp/xray.zip",
    "unzip /tmp/xray.zip -d /tmp/",
    "chmod +x /tmp/xray",
    "mv /tmp/xray /usr/local/bin/",
    "mkdir -p /usr/local/etc/xray"
]

[phases.install]
cmds = [
    "pip3 install --upgrade pip",
    "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
    "cp config.json /usr/local/etc/xray/config.json"
]

[start]
cmd = "sh -c 'xray run -config /usr/local/etc/xray/config.json & python3 main.py'"
