[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget unzip",
    "wget https://github.com/XTLS/Xray-core/releases/download/v1.8.4/Xray-linux-64.zip",
    "unzip Xray-linux-64.zip",
    "chmod +x xray",
    "mv xray /usr/local/bin/",
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "mkdir -p /usr/local/etc/xray",
]

[start]
cmd = "sh -c 'xray run -config /usr/local/etc/xray/config.json & uvicorn main:app --host 0.0.0.0 --port $PORT'"
