[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[env]
PORT = "8000"

# Добавь эту секцию для запуска воркера
[services]
  
  [services.web]
  startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

  [services.worker]
  startCommand = "python bot.py"
