services:
  - type: web
    name: vacvpn-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SHOP_ID
        sync: false
      - key: API_KEY
        sync: false
      - key: TOKEN
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
